[package]
distribution = "2201.0.0"
org = "ballerinax"
name = "aws.s3"
version = "2.2.1"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Content & Files/File Management & Storage", "Cost/Paid", "Vendor/Amazon"]
icon = "icon.png"
repository = "https://github.com/sachinira/module-ballerinax-aws.s3"
