[package]
org = "ballerinax"
name = "aws.s3"
version = "2.0.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Content & Files/File Management & Storage", "Cost/Paid", "Vendor/Amazon"]
repository = "https://github.com/sachinira/module-ballerinax-aws.s3"
