name: Deployment

on: [release]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action/@master
        with:
          args: build -c
      - name: Ballerina Push
        uses: ballerina-platform/ballerina-action/@master
        with:
          args: push
        env:
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}
